name: case_i

time_config:
  start_date: 2016-11-14T00:00:00
  end_date: 2016-11-20T00:00:00
  horizon: 1days
  exp_class: td

region_config:
  region: nz_csep_region
  mag_min: 4.0
  mag_max: 8.0
  mag_bin: 0.1
  depth_min: 0
  depth_max: 70

force_rerun: True
catalog: catalog.csep
model_config: models.yml
test_config: tests.yml
postprocess:
  plot_forecasts:
    all_time_windows: True

