name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [ main ]

jobs:
  build:
    if: github.repository == 'cseptesting/floatcsep'
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11']
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4.2.2
    - uses: mamba-org/setup-micromamba@v1
      with:
        generate-run-shell: true
        environment-file: environment.yml
        create-args: >-
          python=${{ matrix.python-version }}

    - name: Install floatCSEP
      run: |
        pip install -e .[dev]
        python -c "import floatcsep; print('Version: ', floatcsep.__version__)"

    - name: Test with pytest
      run: |
        pytest --durations=0

    - name: Upload coverage
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.10'
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: false